[phases.setup]
nixPkgs = ["python311", "libpq", "gcc"]

[phases.install]
cmds = [
    "python -m venv /app/.venv",
    ". /app/.venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "gunicorn main:app --timeout 120"